
export interface Product {
  id: number;
  category: string;
  gender: string;
  age_group: string;
  style: string;
  fit: string;
  color: string;
  material: string;
  price: number;
  sustainable: boolean;
  occasion: string;
  image_url: string;
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'bot';
  text: string;
  product?: Product;
  isLoading?: boolean;
}

// Gemini output structure matching the schema we will send
export interface ExtractedAttributes {
  // Conversation fields
  bot_response: string; // The natural language response generated by Gemini
  search_intent: boolean; // Whether the user is actually looking for a product

  // Search filters
  category: string | null;
  color: string | null;
  material: string | null;
  occasion: string | null;
  fit: string | null;
  style: string | null;
  gender: string | null;
  
  // Heuristics
  is_cheap: boolean;
  is_expensive: boolean; // NEW: User wants the most expensive item
  is_surprise: boolean;
  is_accenture_special: boolean; // Flag for specific demo item
}
